### ISSUE TITLE
Nil Value in line 702

### ISSUE THREAD

**Issue by Silentfighter89** [eiktyrner/bee#2]
I get an nil Value in line 702, I do not get behind where the error is. I am running on Turtle OS 1.5

**Comment by eiktyrner** [comment]
What version of OpenPeripheral are you using?

It seems like the version you are using is missing the speed attribute in the drone or princess data table.

**Comment by eiktyrner** [comment]
After further investigation it seems like the scoring system changed from a string value to a number.
This http://pastebin.com/8ifxPUkc from Zixxl on the computercraft forum might work. I haven't had time to test it yet. I will see if he/she is interested in merging the changes to this repo.

**Comment by Silentfighter89** [comment]
Hey eiktyrner thanks for the very fast supporting.
 I will try if it works with the one you have suggested thanks

**Comment by Zixxl** [comment]
I send a pull request to this repository to include my latest changes. Please give a update, if my version works (link from eiktyrner) or if there is still an error.

**Comment by eiktyrner** [comment]
Thanks for your contribution Zixxl :+1:

**Comment by Silentfighter89** [comment]
Hey, I did a bit of testing. As far as I can tell, everything works fine.
Thank you very much Zixxl.
