### ISSUE TITLE
bee:583: attempt to index a ? (a nil value)

### ISSUE THREAD

**Issue by ThaeYk** [eiktyrner/bee#7]
Well, I got the error bee:583: attempt to index a ? (a nil value) when trying to run "bee noble"
I think this means that there is a command or something that doesn't exist?
On line 583 it says "tableData = beealyzer.getStackInSlot(9)" my guess is that getStackInSlot() doesn't exist anymore? Are there any fixes to this?
I'm running minecraft 1.7.10
cc 1.65
OpenModsLib-1.7.10-0.6-snapshot-259
OpenPeripheralAddons-1.7.10-0.2.0-snapshot-133
OpenPeripheralCore-1.7.10-0.5.0-snapshot-160

**Comment by eiktyrner** [comment]
This script isn't updated since a year ago. It will not support newer versions of OpenPeripheral.

**Comment by ThaeYk** [comment]
Oh ok. Should it be possible for a noob to update it? I know a little lua, but it might not be enough for it.
Could it be a matter of updating some commands or will I need to redo most of the script?

**Comment by eiktyrner** [comment]
Depends on how much has changed. If you can get the bee data to a table that follows the same schema as the old version it should be possible to use most of the code. 
But maybe it's easier to find someone that already does this but with a newer script. I know at least someone kept working on a new version.

I'm not playing anymore so I won't upgrade (closing this issue now). Feel free to fork the repository though!
